import requests
import json
import random
import time
from pathlib import Path

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "mistral:7b-instruct"

PROJECT_ROOT = Path(__file__).resolve().parents[2]  # ChatLLM/
OUTPUT_PATH = PROJECT_ROOT / "data" / "raw" / "synthetic_chat_dataset.json"
CHECKPOINT_EVERY = 10  # save progress every N users

SEVERITY_LEVELS = ["Ingen", "Lav", "Medium", "Høj"]

# Definitions and prompt has been generated by claude, and has been looked through
GAMBLING_TOPICS = [
    "spilleautomater / slots",
    "sportsbetting (fodbold)",
    "online poker",
    "casino bordspil (roulette, blackjack)",
    "lottoeller skrabelodder",
]

NEUTRAL_TOPICS = [
    "vejret",
    "en film de har set",
    "madopskrifter",
    "weekendplaner",
    "en anden bruger i chatten",
]

TONES = [
    "afslappet og venlig",
    "sarkastisk",
    "irriteret",
    "ophidset/euforisk",
    "trist og resigneret",
    "aggressiv",
]

GRIMT_SPROG_DEFINITIONS = {
    "Ingen": "Beskederne er neutrale eller venlige. Ingen uhøflighed.",
    "Lav": "Mild irritation eller bandeord, men IKKE målrettet en bestemt person (f.eks. 'åh for fanden' eller 'sikke noget lort').",
    "Medium": "Målrettet skæld ud eller gentagen uhøflighed mod en specifik anden bruger i chatten (navngivet eller direkte adresseret).",
    "Høj": "Trusler, chikane, hadefulde udtryk, eller vedholdende målrettet chikane mod en bestemt bruger over flere beskeder.",
}

LUDOMANI_DEFINITIONS = {
    "Ingen": "Ingen tegn på problematisk spiladfærd. Evt. neutral omtale af at spille, vinde eller tabe uden tegn på tab-jagt.",
    "Lav": "Enkeltstående tab-jagt-sprog eller bravade, f.eks. 'det kommer igen' eller 'næste gang vinder jeg det hele tilbage'.",
    "Medium": "Gentagen tab-jagt over flere beskeder, stigende indsatser nævnt, eller bagatellisering af betydelige tab.",
    "Høj": "Eksplicit nødråb, oplevelse af kontroltab, finansiel desperation, omtale af at låne penge eller skjule spil for familie/venner.",
}


def build_prompt(grimt_sprog_level: str, ludomani_level: str, num_messages: int) -> str:
    topic = random.choice(GAMBLING_TOPICS + NEUTRAL_TOPICS)
    tone = random.choice(TONES)

    prompt = f"""Du skal generere syntetiske chatbeskeder til et forskningsprojekt om automatisk detektion af problematisk adfærd i et online chatrum.

Generér {num_messages} beskeder skrevet af ÉN fiktiv chatbruger, på dansk, i et chatrum hvor folk taler om bl.a. online spil/casino.

Konteksten/emnet for beskederne er: {topic}
Tonen skal være: {tone}

Brugerens beskeder skal afspejle PRÆCIS disse to niveauer — ikke mere, ikke mindre alvorligt:

GRIMT SPROG niveau: {grimt_sprog_level}
Definition: {GRIMT_SPROG_DEFINITIONS[grimt_sprog_level]}

TEGN PÅ LUDOMANI niveau: {ludomani_level}
Definition: {LUDOMANI_DEFINITIONS[ludomani_level]}

Reglerne er:
- Hvis et niveau er "Ingen", skal beskederne IKKE indeholde noget signal for den kategori overhovedet.
- Skriv IKKE mere intenst, aggressivt eller alvorligt end det angivne niveau. Eskalér ikke undervejs i beskederne — hold dig konsekvent på det angivne niveau hele vejen igennem.
- Beskederne skal lyde naturlige, som ægte chatbeskeder — korte, uformelle, med slang hvor det passer.
- Skriv på korrekt, naturligt dansk med korrekt grammatik og stavning. Brug ikke opfundne ord, forkerte bøjninger, eller ord der ikke findes på dansk.
- Hvis du er i tvivl om et dansk ord eller udtryk er korrekt, så brug et simplere og mere sikkert ord i stedet.
- Generér KUN beskederne fra denne ene bruger, ikke svar fra andre.

Returnér KUN et JSON-objekt i præcis dette format, uden markdown-formatering, uden forklaring, uden ekstra tekst:

{{
  "messages": ["besked 1", "besked 2", ...]
}}
"""
    return prompt

def call_ollama(prompt: str, model: str = MODEL) -> str:
    response = requests.post(
        OLLAMA_URL,
        json={
            "model": model,
            "prompt": prompt,
            "stream": False,
            "format": "json",
            "options": {
                "temperature": 0.75,  # lower = more conservative, less drift
            },
        },
        timeout=120,
    )
    response.raise_for_status()
    return response.json()["response"]


def extract_messages(raw_response: str) -> list[str]:
    """Parse the model's JSON output, with a fallback for stray formatting."""
    text = raw_response.strip()

    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("json"):
            text = text[4:]
        text = text.strip()

    try:
        parsed = json.loads(text)
        messages = parsed.get("messages", [])
        if isinstance(messages, list) and all(isinstance(m, str) for m in messages):
            return messages
    except json.JSONDecodeError:
        pass

    # Failed to parse — return empty, caller will skip/log this user
    return []


def generate_dataset(num_users: int) -> list[dict]:
    users = []
    failed = 0

    # Build an even-split list of severity combinations to draw from
    grimt_cycle = SEVERITY_LEVELS * ((num_users // len(SEVERITY_LEVELS)) + 1)
    ludomani_cycle = SEVERITY_LEVELS * ((num_users // len(SEVERITY_LEVELS)) + 1)
    random.shuffle(grimt_cycle)
    random.shuffle(ludomani_cycle)

    for i in range(num_users):
        grimt_level = grimt_cycle[i]
        ludomani_level = ludomani_cycle[i]
        num_messages = random.randint(2, 5)

        prompt = build_prompt(grimt_level, ludomani_level, num_messages)

        try:
            raw = call_ollama(prompt)
            messages = extract_messages(raw)
        except requests.exceptions.RequestException as e:
            print(f"[{i+1}/{num_users}] Request failed: {e}")
            messages = []

        if not messages:
            print(f"[{i+1}/{num_users}] Failed to parse JSON, skipping. Raw: {raw[:120] if 'raw' in dir() else 'N/A'}")
            failed += 1
            continue

        user_record = {
            "user_id": i + 1,
            "messages": messages,
            "grimt_sprog_severity": grimt_level,
            "ludomani_severity": ludomani_level,
        }
        users.append(user_record)

        print(f"[{i+1}/{num_users}] OK — grimt={grimt_level}, ludomani={ludomani_level}, msgs={len(messages)}")

        # Checkpoint periodically
        if (i + 1) % CHECKPOINT_EVERY == 0:
            save_dataset(users)
            print(f"  -> checkpoint saved ({len(users)} users so far)")

    print(f"\nDone. {len(users)} users generated, {failed} failed/skipped.")
    return users


def save_dataset(users: list[dict]) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(users, f, ensure_ascii=False, indent=2)


if __name__ == "__main__":
    NUM_USERS = 1000  # adjust as needed

    start = time.time()
    dataset = generate_dataset(NUM_USERS)
    save_dataset(dataset)
    elapsed = time.time() - start

    print(f"\nSaved {len(dataset)} users to {OUTPUT_PATH}")
    print(f"Total time: {elapsed:.1f}s ({elapsed/max(len(dataset),1):.1f}s per user)")